### ISSUE TITLE
Event counter updated on perturbations?

### ISSUE THREAD

**Issue by hmedina** [jonathan-laurent/KaTie#12]
For the concrete example: https://github.com/jonathan-laurent/KaTie/tree/hmedina-dev/tests/unit/measure_sim_event_id

```
'step_index', 'time', 'sim_event_id'
0, 0, 0
1, 1.7935983629643002, 1
2, 1.8292313230569146, 2
3, 3.9882686236387492, 3
4, 3.9882686236387492, 4
5, 4.1773417501450769, 4
6, 5.1611508358723199, 5
```

Note how steps 3 & 4 have the same time value; this is expected because step 3 triggered a perturbation that does not advance time. However, note how steps 4 & 5 have the same event identifier value.

If step 3 did not advance time, why did it advance the event id? Conversely, why did step 4 not advance the event id?

**Comment by jonathan-laurent** [comment]
This is a KaSim issue and not a Katie issue, since all KaTie is doing to report sim_event_id is read a field in the trace file. Thus, the real question is: why does KaSim behave this way?

One would have to consult the manual regarding what the behavior of [E] is supposed to be. One possibility is that it was never intended as a way to identify events but rather as a “rule counter” that is incremented every time a rule is applied, which would explain the behavior you are seeing here. If this is the case, it should be renamed, both in the KaSim API and in KaTie. If not, the behavior must be fixed on KaSim side.

**Comment by hmedina** [comment]
I had hoped to use [E] to identify steps in the trace, but that is clearly not sound. Neither is [T]. For the paper, I'll use KaTIE's "event_id"

**Comment by hmedina** [comment]
Since this is a bigger conversation, touching on nomenclature, manuals, documentation, and other topics on the KaTools side, I'm going to close this issue and continue the conversation on Kappa-Dev/KappaTools#664
