### ISSUE TITLE
when time[e] ignored?

### ISSUE THREAD

**Issue by hmedina** [jonathan-laurent/KaTie#8]
Running the following query:
```
match e: { }
    when rule[e] = 'p' && 0.014 < time[e] && time[e] < 0.015
    return snapshot[.e]
```
on a trace produced by the catphos.ka test model (i.e. as port of `make test`) yields thousands of snapshots whose event number is outside the range specified by the `when` clause of the query.

For example:
```
$ ./query -q tests/snapshotter.query -t tests/catphos/t.json --output-directory foo --native-snapshots --skip-init-events
Queries successfully compiled.
Finding matchings...
Events processed: 90000
Possible matchings found: 94963
Executing actions...
^Ctchings processed: 0%
```
(user-aborted after 365 snapshots were produced)

Snapshot 1 contains `%def: "T0" "0.000181242"`
Snapshot 190 contains `%def: "T0" "0.0149899"`
Snapshot 365 contains `%def: "T0" "0.0294896"`

Using `with` instead of `when` yields the same behavior:
```
match e: { } with 0.014 < time[e] && time[e] < 0.015
    when rule[e] = 'p'
    return snapshot[.e]
```

What I expected was to take a snapshot of the state just before rule `p` fired, but only for times in `[0.014; 0.015]`.

The `tests/catphos/query` contains
```
match e: { } when rule[e] = 'p' return time[e], rule[e]
```
and so from running that query, I know this specific run only has 3 such events and so should produce only 3 snapshots. Given that other query works, the capacity to take time measurements (`time[e]`) is working, as is the rule-name filter (`rule[e]`), so this suggests an issue in using said filters in the event constraining.

Am I using the wrong syntax?

**Comment by jonathan-laurent** [comment]
You are using the correct syntax here.
If you look at the CSV output file, you'll see that the filter worked:

```csv
0.0143, 'p', 'out/snapshot.183.ka'
0.0147, 'p', 'out/snapshot.203.ka'
0.0148, 'p', 'out/snapshot.217.ka'
```

However, many spurious snapshots are taken and saved that are not referenced in the query result.

The reason for this suboptimal behavior is that the current engine evaluates all measures taken in the action branch **before** it evaluates the **when** clause. This was originally perfectly fine since measures were cheap to evaluate and did not have side effects. When I later implemented `snapshot` as a quick hack following a request from you, I accidentally violated these assumptions. I am surprised we did not catch it before though.

Fixing this would require a little work. Could this wait until Monday?

**Comment by hmedina** [comment]
Hi Jonathan, yes it can wait. I'm glad to hear it's just a problem with the operation order, rather than something in the matching logic. I can work on my other queries in the meantime.

**Comment by jonathan-laurent** [comment]
I tried and pushed a fix. This was more complicated than I expected!
There are still unavoidable cases where more snapshots will be stored on disk that you would expect. For example:

```
match e1: {...}
and first e2: {...} after e1
when 10 < time[e2] < 20
return snapshot[.e1]
```

In this case, you may have spurious snapshots on disk (although they won't be referenced in the CSV output). This is because the TQL streams through the trace and when it encounters e1, it cannot know whether or not the when clause will be true for e2 and so it has to take a snapshot just in case.

**Comment by hmedina** [comment]
Thanks Jonathan, I'll incorporate some time-checks into my analysis to remove the out-of-bounds snapshots should they arise.

**Comment by jonathan-laurent** [comment]
>  I'll incorporate some time-checks into my analysis to remove the out-of-bounds snapshots should they arise.

@hmedina The right way to deal with this is to look at the CSV output file of your query. Every snapshot name that is not mentioned in there should not have been taken and can be removed from disk safely (arguably, I could write a third pass that does exactly this).
